server:
  port: 8189
  servlet:
    context-path: /subscriptions

spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5435/subscriptionDb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
swagger-ui:
  enabled: true