version: "3.8"

services:
  app:
    container_name: subscription-app
    ports:
      - "8181:8181"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/subscriptionDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8181
      - SERVER_SERVLET_CONTEXT_PATH=/subscriptions
    networks:
      - net
    restart: unless-stopped

  db:
    image: postgres:15.2-alpine
    container_name: subscription-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=subscriptionDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - subscription_postgres:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
  subscription_postgres: